name: Dart

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: dart-lang/setup-dart@v1

      - name: Install dependencies
        run: dart pub get

      - name: Run tests
        run: dart test

      - name: Analyze package with Pana
        run: |
          pub global activate pana

          # Require full points to pass.
          # TODO: this should be set to zero, but it needs to be 10 until these PRs are merged:
          # - https://github.com/dart-lang/pana/pull/924
          # - https://github.com/dart-lang/pana/pull/925
          pana --no-warning --line-length=120 --exit-code-threshold=10
