name: Dart

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: dart-lang/setup-dart@v1
        with:
          sdk: beta

      # Required in lieu of https://github.com/dart-lang/pana/issues/843
      #- uses: subosito/flutter-action@v1
      #  with:
      #    channel: stable

      - name: Install dependencies
        run: dart pub get

      - name: Run tests
        run: dart test

      - name: Analyze package with Pana
        run: |
          pub global activate pana

          # Require full points to pass.
          # TODO: have to set to 1 until this is merged: https://github.com/dart-lang/pana/pull/924
          pana --no-warning --exit-code-threshold=1
